---
name: Validate YAML Syntax
on: [pull_request]
jobs:
  changedfiles:
    runs-on: ubuntu-latest
    # Map a step output to a job output
    outputs:
      all: ${{ steps.changes.outputs.all}}
    steps:
      # Make sure we have some code to diff.
      - name: Checkout repository
        uses: actions/checkout@v2
        with:
          fetch-depth: 2
      - name: Get changed files
        id: changes
        # Set outputs using the command.
        run: |
          echo "::set-output name=all::$(git diff --name-only --diff-filter=ACMRT ${{ github.event.pull_request.base.sha }} ${{ github.sha }} | xargs)"
  yaml-lint:
    runs-on: ubuntu-latest
    needs: changedfiles
    steps:
#      - run: echo "The job was automatically triggered by a ${{ github.event_name }} event."
#      - run: echo "This job is now running on a ${{ runner.os }} server hosted by GitHub!"
#      - run: echo "The name of your branch is ${{ github.ref }} and your repository is ${{ github.repository }}."
#      - name: Check out repository code
#        uses: actions/checkout@v2
#      - run: echo "The ${{ github.repository }} repository has been cloned to the runner."
#      - run: echo "The workflow is now ready to test your code on the runner."
#      - name: List files in the repository
#        run: |
#          ls ${{ github.workspace }}
#      - run: echo "This job's status is ${{ job.status }}."
#      - run: echo ${{needs.changedfiles.outputs.all}}
      - name: Lint YAML Files
        run: |
          for file in ${{ needs.changed_files.outputs.changed_files }}; do
            yamllint -d "{rules: {line-length: {max: 999}}}" -f github ${{ github.workspace }}/$file
          done
      # in the future hopefully we can lint all yaml files
      #      - name: Run yamllint
      #        uses: frenck/action-yamllint@v1
  yaml-schema:
    runs-on: ubuntu-latest
    needs: [changedfiles,yaml-lint]
    steps:
      - run: npm install -g pajv
      - run: |
          for file in ${{ steps.files.outputs.all }}; do
            if [[ $file == mirrors.d/* ]] ;
            then
              pajv validate -s ci/mirror_config_schema.json -d $file
            fi
          done
  nominatim-check:
    runs-on: ubuntu-latest
    needs: [changedfiles,yaml-lint,yaml-schema]
    steps:
      - name: Validate nominatim lookup2
        run: |
          for file in ${{ steps.files.outputs.all }}; do
            if [[ $file == mirrors.d/* ]] ;
            then
              echo "Checking geolocation data against Nominatim for $file"
              COUNTRY=$(cat ${{ github.workspace }}/$file | shyaml get-value geolocation.country)
              STATE=$(cat ${{ github.workspace }}/$file | shyaml get-value geolocation.state_province)
              CITY=$(cat ${{ github.workspace }}/$file | shyaml get-value geolocation.city)
              NOMINATIM_LOOKUP=$(curl -s "https://nominatim.openstreetmap.org/search?city=$CITY&state=$STATE&country=$COUNTRY&format=json")
              MATCHES=$(echo $NOMINATIM_LOOKUP | jq length)
              echo $MATCHES
              if [[ "$MATCHES" == "0" ]]; then
                echo "$file contains invalid geolocation data"
                exit 1
              else
                echo "Valid geolocation data found for $file"
              fi
            fi
          done
